# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('names', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=10)),
            ],
        ),
    ]
