# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='names',
            name='student_id',
        ),
    ]
