# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_remove_names_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='names',
            name='roll',
        ),
    ]
